/**
 * New Template - L99
 * Generated by v7.4 Template Builder
 */

function renderL99(content) {
  return `
    <section data-layout="L99" class="content-slide grid-container">
      <div class="heading-primary color-primary" style="grid-row-start: 3; grid-column-start: 5; grid-row-end: 5; grid-column-end: 21; font-family: Montserrat, sans-serif; font-size: 36px">
        ${content.element_1 || ''}
      </div>
    </section>
  `;
}

// Export for v7.5
if (typeof window !== 'undefined') {
  window.renderL99 = renderL99;
}
